### ISSUE TITLE
This works Livecheck?

### ISSUE THREAD

**Issue by inode64** [Tatsh/livecheck#177]
I have tried updating my portage but it doesn't work
I have been attempting different parameters but with the same result
I pass the log

<pre>
$ livecheck -d -a sys-process/pm2 
2024-09-20 13:00:06.296 | DEBUG    | livecheck.main:get_props:101 - search_dir=/xxx/inode64-overlay
DEBUG:asyncio:Using selector: EpollSelector
DEBUG:livecheck.utils.portage:Checking: /usr/portage/local/inode64 == /xxx/inode64-overlay ?
</pre>

My overlay is https://github.com/inode64/inode64-overlay

**Comment by Tatsh** [comment]
Unfortunately because of the way the Portage API works, you either have to run livecheck in `/usr/portage/local/inode64` (the real path Portage uses) or you have to add `/xxx/inode64-overlay` to your list of overlays so Portage can see it. This is especially important if you are intending to take the place of a package in another repository (like the main one).

```python
import portage
P = portage.db[portage.root]['porttree'].dbapi
P.xmatch('match-visible', name_of_package) # name_of_package must be something findable with `emerge --search` or equivalent
```
